custom-model-data:
  calm-slime: 404
  active-slime: 200
bucket-title: <!italic><lang:item.slimeinabukkit.slime_bucket>

slime-chunk-message: <gray>This chunk </gray><chunk-status><gray> a Slime chunk
chunk-status:
  'true': <green>is
  'false': <red>is not

can-pickup-slime: true

debug: false